#!/usr/bin/env python2

import os
import subprocess
import time


for path in os.environ['NAUTILUS_SCRIPT_SELECTED_FILE_PATHS'].split('\n'):

  if not path:
    continue

  (dirname, filename) = os.path.split(path)
  title = os.path.split(dirname)[1]
  output_filename = title + '.mp3'
  output_path = os.path.join(dirname, output_filename)

  if os.path.isfile(output_path):
      continue

  cmd = 'lame --quiet --preset standard --tt "%s" ' \
        '--ta "beat cleaver" "%s" "%s"' % (title, path, output_path)
  print "Running...", cmd
  subprocess.check_output(cmd, shell=True)
  print '------'

  link_path = os.path.join(os.path.dirname(dirname), output_filename)
  if os.path.exists(link_path):
    if os.path.islink(link_path):
        os.unlink(link_path)
    else:
        print "Parent exists and is not a link: %s" % link_path
        exit(1)

  cmd = 'ln -s "%s" "%s"' % (output_path, link_path)
  subprocess.check_output(cmd, shell=True)

  done = os.path.join(dirname, '__DONE__')
  open(done, 'w').close()
  time.sleep(2)
  os.unlink(done)
